name: Retrain & Build Docker (CI)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      # =========================
      # 1. CHECKOUT CODE
      # =========================
      - name: Checkout repository
        uses: actions/checkout@v4

      # =========================
      # 2. SETUP PYTHON
      # =========================
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # =========================
      # 3. INSTALL DEPENDENCIES
      # =========================
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn xgboost

      # =========================
      # 4. RETRAIN MODEL (MLFLOW)
      # =========================
      - name: Retrain model with MLflow Project
        run: |
          cd MLProject
          export MLFLOW_TRACKING_URI=file:$(pwd)/mlruns
          mlflow run . --env-manager=local

      # =========================
      # 5. COMMIT MLFLOW ARTIFACTS
      # (SKILLED – 3 POIN)
      # =========================
      - name: Save MLflow artifacts to repository
        run: |
          cd MLProject
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add mlruns
          git commit -m "Save MLflow artifacts [CI]" || echo "No changes to commit"
          git push

      # =========================
      # 6. LOGIN DOCKER HUB
      # =========================
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # =========================
      # 7. BUILD DOCKER IMAGE
      # (ADVANCE – 4 POIN)
      # =========================
      - name: Build Docker image with MLflow
        env:
          MLFLOW_TRACKING_URI: file:./MLProject/mlruns
        run: |
          RUN_ID=$(ls MLProject/mlruns/0 | head -n 1)
          echo "Using RUN_ID=$RUN_ID"

          mlflow models build-docker \
            -m runs:/$RUN_ID/model \
            -n ${{ secrets.DOCKERHUB_USERNAME }}/telco-offer-ml:latest

      # =========================
      # 8. PUSH DOCKER IMAGE
      # =========================
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/telco-offer-ml:latest
