name: Retrain & Build Docker

on:
  push:
    branches: [ main ]

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env
          auto-activate-base: false

      # TRAIN MODEL (NO MLFLOW)
      - name: Train Model
        shell: bash -l {0}
        run: |
          cd MLProject
          python modelling.py

      # LOGIN DOCKER
      - name: Login Docker Hub
        shell: bash -l {0}
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      # BUILD DOCKER
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/telco-offer-ml .

      # PUSH DOCKER
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/telco-offer-ml
