name: Retrain & Build Docker

on:
  push:
    branches: [ main ]

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env
          auto-activate-base: false

      # ðŸ”‘ AUTH DAGSHUB (BENAR & FINAL)
      - name: Set MLflow Tracking to DagsHub
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/mrone2104/telco-offer-mlflow.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=dagshub" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      # ðŸ”´ JANGAN mlflow run .
      - name: Train Model
        shell: bash -l {0}
        run: |
          cd MLProject
          python modelling.py

      - name: Login Docker Hub
        shell: bash -l {0}
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      - name: Build Docker Image
        shell: bash -l {0}
        run: |
          cd MLProject
          RUN_ID=$(cat run_id.txt)
          mlflow models build-docker \
            -m runs:/$RUN_ID/model \
            -n ${{ secrets.DOCKERHUB_USERNAME }}/telco-offer-ml

      - name: Push Docker Image
        shell: bash -l {0}
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/telco-offer-ml
