name: Retrain & Build Docker (CI)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow pandas scikit-learn xgboost

      - name: Retrain model
        env:
          MLFLOW_TRACKING_URI: file:./mlruns
        run: |
          cd MLProject
          python modelling.py

      - name: Debug mlruns
        run: |
          echo "=== TREE MLProject ==="
          ls -R MLProject

      - name: Get model path
        run: |
          MODEL_PATH=$(find MLProject/mlruns -type d -name model | head -n 1)
          echo "MODEL_PATH=$MODEL_PATH"
          echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_ENV
          if [ -z "$MODEL_PATH" ]; then
            echo "MODEL_PATH not found"; exit 1;
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image (MLflow)
        run: |
          mlflow models build-docker \
            -m "$MODEL_PATH" \
            -n ${{ secrets.DOCKERHUB_USERNAME }}/telco-offer-ml:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/telco-offer-ml:latest
