name: Retrain & Build Docker (CI)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install mlflow pandas scikit-learn xgboost matplotlib seaborn

    - name: Train model with MLflow
      run: |
        cd MLProject
        python modelling.py

    # ðŸ” DEBUG (boleh dihapus setelah hijau)
    - name: Debug MLruns structure
      run: |
        ls -R MLProject/mlruns

    # ðŸ”‘ AMBIL EXP_ID & RUN_ID DARI STRUKTUR ASLI
    - name: Get latest run id
      run: |
        EXP_ID=$(ls MLProject/mlruns | grep -v models | grep -v trash | head -1)
        RUN_ID=$(ls MLProject/mlruns/$EXP_ID | head -1)
        echo "EXP_ID=$EXP_ID" >> $GITHUB_ENV
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Experiment: $EXP_ID"
        echo "Run: $RUN_ID"

    - name: Build Docker Image with MLflow
      run: |
        mlflow models build-docker \
          -m MLProject/mlruns/$EXP_ID/$RUN_ID/artifacts/model \
          -n riskinanda/telco-offer-ml

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: |
        docker push riskinanda/telco-offer-ml
