name: Retrain & Build Docker (CI)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow pandas scikit-learn xgboost

      # =====================
      # RETRAIN MODEL
      # =====================
      - name: Retrain model
        run: |
          cd MLProject
          export MLFLOW_TRACKING_URI=file:$(pwd)/mlruns
          python modelling.py

      # =====================
      # BUILD DOCKER (PAKAI DOCKERFILE)
      # =====================
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/telco-offer-ml:latest MLProject

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/telco-offer-ml:latest
