name: Retrain & Build Docker (CI)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    # ===============================
    # Checkout repository
    # ===============================
    - name: Checkout repository
      uses: actions/checkout@v4

    # ===============================
    # Set up Python
    # ===============================
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # ===============================
    # Install dependencies
    # ===============================
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install mlflow pandas scikit-learn xgboost matplotlib seaborn

    # ===============================
    # Train model with MLflow
    # ===============================
    - name: Train model with MLflow
      run: |
        cd MLProject
        python modelling.py

    # ===============================
    # Read latest MLflow run id
    # ===============================
    - name: Read latest MLflow run id
      run: |
        RUN_ID=$(cat MLProject/latest_run.txt)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV_
