name: Retrain & Build Docker (CI)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    # ===============================
    # Checkout repository
    # ===============================
    - name: Checkout repository
      uses: actions/checkout@v4

    # ===============================
    # Set up Python
    # ===============================
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # ===============================
    # Install dependencies
    # ===============================
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install mlflow pandas scikit-learn xgboost matplotlib seaborn

    # ===============================
    # Train model (MLflow logging)
    # ===============================
    - name: Train model with MLflow
      run: |
        cd MLProject
        python modelling.py

    # ===============================
    # DEBUG: cek lokasi mlruns
    # ===============================
    - name: Debug MLflow artifacts
      run: |
        echo "=== ROOT ==="
        pwd
        ls -la
        echo "=== MLProject ==="
        ls -la MLProject
        echo "=== mlruns ==="
        ls -R MLProject/mlruns || echo "mlruns tidak ditemukan"

    # ===============================
    # Login Docker Hub
    # ===============================
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # ===============================
    # Build Docker Image (AUTO latest)
    # ===============================
    - name: Build Docker Image with MLflow
      run: |
        mlflow models build-docker \
          -m MLProject/mlruns/*/*/artifacts/model \
          -n riskinanda/telco-offer-ml

    # ===============================
    # Push Docker Image
    # ===============================
    - name: Push Docker Image
      run: |
        docker push riskinanda/telco-offer-ml

    # ===============================
    # Upload MLflow Artifacts (bukti CI)
    # ===============================
    - name: Upload MLflow Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: MLProject/mlruns
