name: Retrain & Build Docker (CI)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    # ===============================
    # Checkout repository
    # ===============================
    - uses: actions/checkout@v4

    # ===============================
    # Setup Python
    # ===============================
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # ===============================
    # Install Python dependencies
    # ===============================
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pandas scikit-learn xgboost mlflow

    # ===============================
    # Train model
    # ===============================
    - name: Train model
      run: |
        cd MLProject
        python modelling.py

    # ===============================
    # Login Docker Hub
    # ===============================
    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # ===============================
    # Build Docker Image
    # ===============================
    - name: Build Docker Image
      run: |
        docker build -t riskinanda/telco-offer-ml ./MLProject

    # ===============================
    # Push Docker Image
    # ===============================
    - name: Push Docker Image
      run: |
        docker push riskinanda/telco-offer-ml
